import { useState } from 'react';
import { orgApi, workflowApi } from '../services/api.js';
import { useAsyncData } from '../hooks/useAsyncData.js';
import { Button, Card, Field, Input, PageHeader, Select, SimpleTable, StatusBadge } from '../components/ui.jsx';

export default function Audit() {
  const { data: audits = [], refresh } = useAsyncData(workflowApi.audits, [], 0, []);
  const { data: departments = [] } = useAsyncData(orgApi.departments, [], 0, []);
  const { data: users = [] } = useAsyncData(orgApi.users, [], 0, []);
  const [form, setForm] = useState({ name: '', scopeType: 'DEPARTMENT', scopeValue: '', startDate: '', endDate: '', auditorUserIds: [] });
  async function submit(e) { e.preventDefault(); await workflowApi.createAudit({ ...form, auditorUserIds: form.auditorUserIds.filter(Boolean) }); refresh(); }
  const items = audits.flatMap((a) => (a.items || []).map((item) => ({ ...item, cycleName: a.name, cycleStatus: a.status })));
  return <div className="grid gap-6"><PageHeader eyebrow="Audit Assurance" title="Structured Asset Audits" description="Create scoped cycles, assign auditors, flag discrepancies, then close and lock results." /><Card><form onSubmit={submit} className="grid gap-3 md:grid-cols-3"><Field label="Cycle name"><Input required value={form.name} onChange={(e) => setForm({ ...form, name: e.target.value })} /></Field><Field label="Department scope"><Select required value={form.scopeValue} onChange={(e) => setForm({ ...form, scopeValue: e.target.value })}><option value="">Select</option>{departments.map((d) => <option key={d.id} value={d.id}>{d.name}</option>)}</Select></Field><Field label="Auditor"><Select value={form.auditorUserIds[0] || ''} onChange={(e) => setForm({ ...form, auditorUserIds: [e.target.value] })}><option value="">Select</option>{users.map((u) => <option key={u.id} value={u.id}>{u.name}</option>)}</Select></Field><Field label="Start"><Input type="date" required value={form.startDate} onChange={(e) => setForm({ ...form, startDate: e.target.value })} /></Field><Field label="End"><Input type="date" required value={form.endDate} onChange={(e) => setForm({ ...form, endDate: e.target.value })} /></Field><Button className="self-end">Create Audit Cycle</Button></form></Card><Card><h2 className="mb-3 text-xl font-black">Audit Cycles</h2><SimpleTable columns={[{ key: 'name', label: 'Cycle' }, { key: 'scopeType', label: 'Scope' }, { key: 'status', label: 'Status', render: (r) => <StatusBadge value={r.status} /> }, { key: 'items', label: 'Items', render: (r) => r.items?.length || 0 }]} rows={audits} renderActions={(r) => r.status !== 'CLOSED' && <Button onClick={() => workflowApi.closeAudit(r.id).then(refresh)}>Close & Lock</Button>} /></Card><Card><h2 className="mb-3 text-xl font-black">Audit Items</h2><SimpleTable columns={[{ key: 'cycleName', label: 'Cycle' }, { key: 'asset', label: 'Asset', render: (r) => r.asset?.name }, { key: 'result', label: 'Result', render: (r) => <StatusBadge value={r.result} /> }, { key: 'notes', label: 'Notes' }]} rows={items} renderActions={(r) => r.cycleStatus !== 'CLOSED' && <div className="flex justify-end gap-2"><Button variant="secondary" onClick={() => workflowApi.markAuditItem(r.id, { result: 'VERIFIED', notes: 'Seen physically' }).then(refresh)}>Verified</Button><Button variant="secondary" onClick={() => workflowApi.markAuditItem(r.id, { result: 'DAMAGED', notes: 'Needs repair' }).then(refresh)}>Damaged</Button><Button variant="danger" onClick={() => workflowApi.markAuditItem(r.id, { result: 'MISSING', notes: 'Not found' }).then(refresh)}>Missing</Button></div>} /></Card></div>;
}
